id: I57985611
legacy_id: P001802
ocr_import_info:
  bdrc_scan_id: W19988
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:51:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:48:49.279335+00:00'
last_modified: 2022-08-30 23:49:14.343023
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19988
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW19988
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀམ་ཚང་གསེར་ཕྲེང་གི་རྣམ་ཐར་ཁ་སྐོང་།
  author: རྗེ་དབོན་གྲགས་པ་ཡོངས་འདུས།
statistics:
  ocr_word_mean_confidence_index: 0.8803739493410394
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1GS55134:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS55134
      total_pages: 404
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS55134.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8803739493410394
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
