id: P001802
initial_creation_type: ocr
source_metadata:
  id: bdr:W19988
  title: ཀམ་ཚང་གསེར་ཕྲེང་གི་རྣམ་ཐར་ཁ་སྐོང
  author: ''
  volumes:
    bdc52af318ec426b9d710c65ddf627aa:
      image_group_id: I1GS55134
      title: ''
      volume_number: 1
      total_pages: 404
      base_file: v001.txt
